site_name: Web Programming Peports Stash
theme:
  name: terminal
  features:
   - revision.date
  plugins:
   - search
   - git-revision-date
  language: en
        
repo_url: https://github.com/MaksNick/ITMO_ICT_WebDevelopment_2023-2024
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys

nav:
  - Home: index.md
  - Lab 1:
      - Intro: lab1/index.md
      - Task 1: lab1/task1.md
      - Task 2: lab1/task2.md
      - Task 3: lab1/task3.md
      - Task 4: lab1/task4.md
      - Task 5: lab1/task5.md
  - Lab 2:
    - Intro: lab2/index.md
    - Assessment: lab2/variant.md
    - Models: lab2/models.md
    - Views: lab2/views.md
    - Forms and URLs: lab2/forms.md
  - Practice 3:
    - Intro: practice3/index.md
    - Part 1: practice3/part1.md
    - Part 2: practice3/part2.md
  - Lab 3:
    - Intro: lab3/index.md
    - Models: lab3/models.md
    - Views and serializers: lab3/views.md
    - Signals: lab3/signals.md